### ISSUE TITLE
Refactoring of layer parameters as tuples where possible

### ISSUE THREAD

**Issue by isaak-l** [lucasb-eyer/DeepFried2#45]
I'm thinking of starting the refactoring effort for the parameters of layers.
Changing some of them to tuples would allow us to have more general layers that are agnostic towards 2D or 3D (4D or 5D tensors respectively) input. This would also allow us to merge some layers.

@lucasb-eyer have you already started with this and have a magical branch lying around somewhere?

**Comment by lucasb-eyer** [comment]
No, I haven't started it. I'd be very happy if you took care of it since I'm super busy lately. That reminds me that I also never merged your 3d conv/pool PRs that you will need for this; let me merge them right now.

**Comment by isaak-l** [comment]
Should we close this issue now?

**Comment by lucasb-eyer** [comment]
Good call, thanks.
