### ISSUE TITLE
RGB vs BGR problems in image loading for the VGG example

### ISSUE THREAD

**Issue by Pandoro** [lucasb-eyer/DeepFried2#78]
The image in the [VGG example](https://github.com/lucasb-eyer/DeepFried2/blob/4ce8d42/examples/Pretrained/run_vgg.py#L40) is possibly read with cv2.imread resulting in a BGR image instead of the likely expected RGB. This might very well screw with the predictions, because we all red grass right?

**Comment by lucasb-eyer** [comment]
Thanks. As I noted in the commit, interestingly, it doesn't change much in the VGG predictions in the single ImageNet validation image I tested it with.
