### ISSUE TITLE
MNIST example fails due to missing progressbar

### ISSUE THREAD

**Issue by Pandoro** [lucasb-eyer/DeepFried2#9]
Running the MNIST example fails as progressbar is not found. I was able to solve this issue by copying the `utils.py` in the examples folder and adapting the import. This might have been due to a wrong installation though, based on Issue #8 ;).

**Comment by lucasb-eyer** [comment]
It might be a bug, because installation shouldn't move things around. I'll check it out.

**Comment by lucasb-eyer** [comment]
I actually uninstalled progressbar on my machine and the MNIST example still works, using the progressbar from `utils.py`. I'd like to look at this on your machine sometime soon.

**Comment by lucasb-eyer** [comment]
Closing for non-reproducibility.
